import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import oru.inf.InfDB;
import oru.inf.InfException;


/**
 *
 * @author erikr
 */
public class Agent extends javax.swing.JFrame {
    private InfDB idb;
    /**
     * Creates new form Agent
     */
    public Agent(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        lblRegistrera = new javax.swing.JLabel();
        btnRegistrera = new javax.swing.JButton();
        lblSokAgent = new javax.swing.JLabel();
        txtSokAgent = new javax.swing.JTextField();
        btnSokAgent = new javax.swing.JButton();
        lblChefAndra = new javax.swing.JLabel();
        btnChefAndra = new javax.swing.JButton();
        lblAndraAdmin = new javax.swing.JLabel();
        btnAdminAndra = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblRegistrera.setText("Registrera agent");

        btnRegistrera.setText("Registrera");
        btnRegistrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraActionPerformed(evt);
            }
        });

        lblSokAgent.setText("Sök efter Agent");

        btnSokAgent.setText("Sök");
        btnSokAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokAgentActionPerformed(evt);
            }
        });

        lblChefAndra.setText("Ändra chefer för agenter");

        btnChefAndra.setText("Ändra");
        btnChefAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChefAndraActionPerformed(evt);
            }
        });

        lblAndraAdmin.setText("Ändra adminstatus för agenter");

        btnAdminAndra.setText("Ändra");
        btnAdminAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminAndraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegistrera)
                    .addComponent(btnRegistrera))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSokAgent)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSokAgent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSokAgent, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChefAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChefAndra)
                    .addComponent(lblAndraAdmin)
                    .addComponent(btnAdminAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblChefAndra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChefAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAndraAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdminAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSokAgent)
                    .addComponent(lblRegistrera))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSokAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSokAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnRegistrera, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraActionPerformed
       if (Validering.getAdminStatus() == true) {
          new RegistreraAgent(idb).setVisible(true);
      }
      else {
          JOptionPane.showMessageDialog(rootPane, "Ej systemadmin");
      }
    }//GEN-LAST:event_btnRegistreraActionPerformed

    private void btnSokAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokAgentActionPerformed
        // TODO add your handling code here:
        String id = DataBasFragor.getAgentID(txtSokAgent.getText());
        
        new TabellAgent(DataBasFragor.getAlltOmEnAgent(id)).setVisible(true);
    }//GEN-LAST:event_btnSokAgentActionPerformed

    private void btnChefAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChefAndraActionPerformed
        if (Validering.getAdminStatus()) {
            new AndraChef(idb).setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Ej systemadmin");

        }
    }//GEN-LAST:event_btnChefAndraActionPerformed

    private void btnAdminAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminAndraActionPerformed
       if (Validering.getAdminStatus() == true) {
          new AndraAdmin(idb).setVisible(true);
      }
      else {
           JOptionPane.showMessageDialog(rootPane, "Ej systemadmin");
       }
    }//GEN-LAST:event_btnAdminAndraActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminAndra;
    private javax.swing.JButton btnChefAndra;
    private javax.swing.JButton btnRegistrera;
    private javax.swing.JButton btnSokAgent;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblAndraAdmin;
    private javax.swing.JLabel lblChefAndra;
    private javax.swing.JLabel lblRegistrera;
    private javax.swing.JLabel lblSokAgent;
    private javax.swing.JTextField txtSokAgent;
    // End of variables declaration//GEN-END:variables
}
