import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import oru.inf.InfDB;
import oru.inf.InfException;


/**
 *
 * @author erikr
 */
public class Agent extends javax.swing.JFrame {
    private InfDB idb;
    /**
     * Creates new form Agent
     */
    public Agent(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        btnRegistrera = new javax.swing.JButton();
        lblSokAgent = new javax.swing.JLabel();
        txtSokAgent = new javax.swing.JTextField();
        btnSokAgent = new javax.swing.JButton();
        btnChefAndra = new javax.swing.JButton();
        btnAdminAndra = new javax.swing.JButton();
        btnTabortAgent = new javax.swing.JButton();
        btnAndraInfoAgent = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnGaTillbaka = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnRegistrera.setText("Registrera agent");
        btnRegistrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraActionPerformed(evt);
            }
        });

        lblSokAgent.setText("Sök efter Agent");

        btnSokAgent.setText("Sök");
        btnSokAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokAgentActionPerformed(evt);
            }
        });

        btnChefAndra.setText("Ändra chefer");
        btnChefAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChefAndraActionPerformed(evt);
            }
        });

        btnAdminAndra.setText("Ändra adminstatus");
        btnAdminAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminAndraActionPerformed(evt);
            }
        });

        btnTabortAgent.setText("Ta bort agent");
        btnTabortAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabortAgentActionPerformed(evt);
            }
        });

        btnAndraInfoAgent.setText("Ändra agentinfo");
        btnAndraInfoAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraInfoAgentActionPerformed(evt);
            }
        });

        jLabel1.setText("Adminfunktioner");

        btnGaTillbaka.setText("Gå tillbaka");
        btnGaTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGaTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSokAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSokAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAndraInfoAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChefAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnAdminAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrera, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTabortAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSokAgent)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGaTillbaka)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChefAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSokAgent)
                    .addComponent(btnAdminAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSokAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSokAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrera, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTabortAgent)))
                .addGap(18, 18, 18)
                .addComponent(btnAndraInfoAgent)
                .addGap(27, 27, 27)
                .addComponent(btnGaTillbaka)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraActionPerformed
       if (Validering.getAdminStatus() == true) {
          new RegistreraAgent(idb).setVisible(true);
      }
      else {
          JOptionPane.showMessageDialog(rootPane, "Ej systemadmin");
      }
    }//GEN-LAST:event_btnRegistreraActionPerformed

    private void btnSokAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokAgentActionPerformed
        // TODO add your handling code here:
        String id = DataBasFragor.getAgentID(txtSokAgent.getText());
        
        new VisaTabellAgent(DataBasFragor.getAlltOmEnAgent(id)).setVisible(true);
    }//GEN-LAST:event_btnSokAgentActionPerformed

    private void btnChefAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChefAndraActionPerformed
        if (Validering.getAdminStatus()) {
            new AndraChef(idb).setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Ej systemadmin");

        }
    }//GEN-LAST:event_btnChefAndraActionPerformed

    private void btnAdminAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminAndraActionPerformed
       if (Validering.getAdminStatus() == true) {
          new AndraAdmin(idb).setVisible(true);
      }
      else {
           JOptionPane.showMessageDialog(rootPane, "Ej systemadmin");
       }
    }//GEN-LAST:event_btnAdminAndraActionPerformed

    private void btnTabortAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabortAgentActionPerformed
        // TODO add your handling code here:
        if (Validering.getAdminStatus()) {
        new TaBortAgent(idb).setVisible(true);
        }
         else {
           JOptionPane.showMessageDialog(rootPane, "Ej systemadmin");
       }
    }//GEN-LAST:event_btnTabortAgentActionPerformed

    private void btnAndraInfoAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraInfoAgentActionPerformed
      if (Validering.getAdminStatus() == true) {
        new AndraInfoAgent(idb).setVisible(true);
      }
      else {
          JOptionPane.showMessageDialog(rootPane, "Ej systemadmin");
      }
    }//GEN-LAST:event_btnAndraInfoAgentActionPerformed

    private void btnGaTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGaTillbakaActionPerformed
        dispose();
    }//GEN-LAST:event_btnGaTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminAndra;
    private javax.swing.JButton btnAndraInfoAgent;
    private javax.swing.JButton btnChefAndra;
    private javax.swing.JButton btnGaTillbaka;
    private javax.swing.JButton btnRegistrera;
    private javax.swing.JButton btnSokAgent;
    private javax.swing.JButton btnTabortAgent;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSokAgent;
    private javax.swing.JTextField txtSokAgent;
    // End of variables declaration//GEN-END:variables
}
