
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfDB;
import oru.inf.InfException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hanna
 */
public class SokEfterEnAlien extends javax.swing.JFrame {

    private InfDB idb;
    /**
     * Creates new form SokEfterEnAlien
     */
    public SokEfterEnAlien(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAngeEpost = new javax.swing.JLabel();
        btnSok = new javax.swing.JButton();
        tfEpost = new javax.swing.JTextField();
        tfNamn = new javax.swing.JTextField();
        btnAndraInfo = new javax.swing.JButton();
        btnAvbryt = new javax.swing.JButton();
        tfNummer = new javax.swing.JTextField();
        tfDatum = new javax.swing.JTextField();
        lblNamn = new javax.swing.JLabel();
        lblNummer = new javax.swing.JLabel();
        lblDatum = new javax.swing.JLabel();
        lblPlats = new javax.swing.JLabel();
        lblAgent = new javax.swing.JLabel();
        cbPlats = new javax.swing.JComboBox<>();
        cbAnsvarigAgent = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblAngeEpost.setText("Ange alien epost:");

        btnSok.setText("Sök");
        btnSok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokActionPerformed(evt);
            }
        });

        tfNamn.setEditable(false);

        btnAndraInfo.setText("Ändra information");
        btnAndraInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraInfoActionPerformed(evt);
            }
        });

        btnAvbryt.setText("Avbryt");
        btnAvbryt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvbrytActionPerformed(evt);
            }
        });

        tfNummer.setEditable(false);

        tfDatum.setEditable(false);

        lblNamn.setText("Namn:");

        lblNummer.setText("Telefonnummer:");

        lblDatum.setText("Registreringsdatum:");

        lblPlats.setText("Plats:");

        lblAgent.setText("Ansvarig agent:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNamn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNummer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDatum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPlats)
                                    .addComponent(lblAgent))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbPlats, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbAnsvarigAgent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAngeEpost)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSok))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnAndraInfo)
                        .addGap(46, 46, 46)
                        .addComponent(btnAvbryt)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(lblAngeEpost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSok))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn)
                    .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlats)
                    .addComponent(cbPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNummer)
                    .addComponent(tfNummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgent)
                    .addComponent(cbAnsvarigAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatum))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvbryt)
                    .addComponent(btnAndraInfo))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvbrytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvbrytActionPerformed
        // Stänger fönstret
        dispose();
    }//GEN-LAST:event_btnAvbrytActionPerformed
           
        //Fyller combobox med platser
    private void FyllPlats() {
        cbPlats.removeAllItems();
    try {
            String fraga ="select Benamning from plats ";
            ArrayList<String> namnLista = idb.fetchColumn(fraga);
            for (String namn :namnLista){
                cbPlats.addItem(namn);
            }
        } catch (InfException ex) {
            Logger.getLogger(RegistreraNyAlien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
         //Fyller combobox med en plats för en specifik alien
    private void FyllPlatsForAlien(String epost) {
            cbPlats.removeAllItems();
            try {
            String fraga ="select Benamning from plats join alien on plats=Plats_ID where epost = '"+epost+"'";
            String namn = idb.fetchSingle(fraga);
                cbPlats.addItem(namn);
            }
         catch (InfException ex) {
            Logger.getLogger(RegistreraNyAlien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
         //Fyller combobox med agenter
    private void FyllAgenter() {
        cbAnsvarigAgent.removeAllItems();
    try {
            String fraga ="select namn from agent ";
            ArrayList<String> namnLista = idb.fetchColumn(fraga);
            for (String namn :namnLista){
                cbAnsvarigAgent.addItem(namn);
            }
        } catch (InfException ex) {
            Logger.getLogger(RegistreraNyAlien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
         //Fyller combobox med en agent för en specifik alien
    private void FyllAgentForAlien(String epost) {
            cbAnsvarigAgent.removeAllItems();
            try {
            String fraga ="select agent.namn from agent join alien on Ansvarig_Agent=Agent_ID where alien.Epost = '"+epost+"'";
            String namn = idb.fetchSingle(fraga);
                cbAnsvarigAgent.addItem(namn);
            }
         catch (InfException ex) {
            Logger.getLogger(RegistreraNyAlien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btnSokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokActionPerformed
       
        if (Validering.textFaltHarVarde(tfEpost) && Validering.alienEpostFinnsSok(tfEpost)) {
        try {
            // Hämta epost
            String epost = tfEpost.getText();
            //samla info om speficik alien via epost (LÄGG TILL RAS(?))
            String namn = idb.fetchSingle("select namn from alien where epost = '" + epost + "'");
            String nummer = idb.fetchSingle("select telefon from alien where epost = '" + epost + "'");
            String datum = idb.fetchSingle("select registreringsdatum from alien where epost = '" + epost + "'");
            
            //printa info i rutorna
            tfNamn.setText(namn);
            tfNummer.setText(nummer);
            tfDatum.setText(datum);
            
            //kallar på metod för att fylla boxarna
            FyllAgentForAlien(epost);
            FyllPlatsForAlien(epost);              
            
        } catch (InfException ex) {
            Logger.getLogger(SokEfterEnAlien.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnSokActionPerformed

    private void btnAndraInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraInfoActionPerformed
        // Lagra titlar
        String epost = tfEpost.getText();
        String knappText = btnAndraInfo.getText();
        String valdText = "Ändra information";
        //Om man trycker på "ändra" sätter det rutorna till förändringsbara
        if (knappText.equals(valdText)) {      
            btnAndraInfo.setText("Spara ändringar");
            tfNamn.setEditable(true);
            tfNummer.setEditable(true);
            tfDatum.setEditable(true);   
            FyllPlats();
            FyllAgenter();
        }
        else {
            try {
                //hämta ny info
                String namn = tfNamn.getText();
                String nummer = tfNummer.getText();
                String datum = tfDatum.getText();
                String plats = cbPlats.getSelectedItem().toString();
                String agent = cbAnsvarigAgent.getSelectedItem().toString();
                
                //Hämta ID för plats & agent
                String platsID = idb.fetchSingle("SELECT plats_ID FROM plats where benamning = '"+plats+"'");
                String agentID = idb.fetchSingle("SELECT agent_ID FROM agent where agent.namn = '"+agent+"'");    
                
                //lagra ny info till databasen
                idb.update("update alien set namn='"+namn+"' where epost='"+epost+"'");
                idb.update("update alien set telefon='"+nummer+"' where epost='"+epost+"'");
                idb.update("update alien set registreringsdatum='"+datum+"' where epost='"+epost+"'");
                idb.update("update alien set Plats = "+platsID+" where epost='"+epost+"'");
                idb.update("update alien set Ansvarig_Agent = "+agentID+" where epost='"+epost+"'");
                
                //Ändra tillbaka till oförändringsbart och fyller boxarna med ett värde igen
                btnAndraInfo.setText(valdText);
                tfNamn.setEditable(false);
                tfNummer.setEditable(false);
                tfDatum.setEditable(false);
                FyllPlatsForAlien(epost);
                FyllAgentForAlien(epost);
                
            } catch (InfException ex) {
                Logger.getLogger(SokEfterEnAlien.class.getName()).log(Level.SEVERE, null, ex);
            }          
        }
    }//GEN-LAST:event_btnAndraInfoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraInfo;
    private javax.swing.JButton btnAvbryt;
    private javax.swing.JButton btnSok;
    private javax.swing.JComboBox<String> cbAnsvarigAgent;
    private javax.swing.JComboBox<String> cbPlats;
    private javax.swing.JLabel lblAgent;
    private javax.swing.JLabel lblAngeEpost;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblNummer;
    private javax.swing.JLabel lblPlats;
    private javax.swing.JTextField tfDatum;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfNamn;
    private javax.swing.JTextField tfNummer;
    // End of variables declaration//GEN-END:variables
}
