
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author erikr
 */
public class TabellAgent extends javax.swing.JFrame {

    private HashMap<String, String> HM;
    /**
     * Creates new form TabellAgent
     */
    public TabellAgent(HashMap<String, String> HM) {
        this.HM = HM;
        initComponents();
    }
    
    public DefaultTableModel sattTabellModell(HashMap<String, String> HM){
        String[] kolumner = {"Namn", "Telnummer", "Anställningsdatum", "Administratör", "Epost", "Omrade", "Agent_ID"};
                
        Collection<String> info = HM.values();
        
        ArrayList<String> infoAgent = new ArrayList<>(info);
        
            
            Object[] rad = infoAgent.toArray();
            Object[][] data = {rad};
        
        
        return new DefaultTableModel(data, kolumner);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ID = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ID.setModel(sattTabellModell(HM));
        jScrollPane1.setViewportView(ID);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ID;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
