
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author erikr
 */
public class Topp3Agent extends javax.swing.JFrame {
    /**
     * Creates new form Topp3Agent
     */
    private ArrayList<HashMap<String, String>> hurMangaAliensPerAgent;
    private DefaultTableModel tabellModell;
    
    public Topp3Agent(ArrayList<HashMap<String, String>> AL) {
        hurMangaAliensPerAgent = AL;
        initComponents();
    }
    
    public DefaultTableModel sattTabellModell(ArrayList<HashMap<String, String>> rader){
        Object[][] data = new Object[rader.size()][2];
        String[] kolumner ={"Agent ID", "Antal Aliens"};
        
        for (int i = 0; i < rader.size(); i++){
            HashMap<String, String> HM = rader.get(i);
            String agentID = HM.get("Ansvarig_Agent");
            String antalAliens = HM.get("row_count");
            
            Object[] rad = {agentID, antalAliens};
            data[i] = rad;
        }
        
        return new DefaultTableModel(data, kolumner);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(sattTabellModell(hurMangaAliensPerAgent));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
