
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author erikr
 */
public class VisaMinUtkvitteradeUtrustning extends javax.swing.JFrame {

    private ArrayList<HashMap<String, String>> AL;
    /**
     * Creates new form VisaMinUtkvitteradeUtrustning
     */
    public VisaMinUtkvitteradeUtrustning(ArrayList<HashMap<String, String>> AL) {
        this.AL = AL;
        initComponents();
        
    }
    
    public DefaultTableModel sattTabellModell(ArrayList<HashMap<String, String>> Lista){
        Object[][] data = new Object[Lista.size()][2];
        String[] kolumner = {"Benämning", "UtrustningsID"};
        
        for(int i = 0; i < Lista.size(); i++){
            HashMap<String, String> HM = Lista.get(i);
            String namn = HM.get("Benamning");
            String utrID = HM.get("Utrustnings_ID");
            
            Object[] rad = {namn, utrID};
            data[i] = rad;
            
        }
        
        return new DefaultTableModel(data, kolumner);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(sattTabellModell(AL));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
